### ISSUE TITLE
`colcon_core.entry_point` deprecation warning on python 3.11

### ISSUE THREAD

**Issue by christophfroehlich** [colcon/colcon-devtools#28]
I wrote a CI pipeline for debian for ros2_control, using debian 12 for the rolling version. This one comes with python 3.11.2, where I get the following deprecation warning:

`/usr/lib/python3/dist-packages/colcon_devtools/verb/extension_points.py:4: UserWarning: 'colcon_core.entry_point' has been deprecated, use 'colcon_core.extension_point' instead`

This was fixed already, but the last release of `colcon-devtools` seems to be missing for python 3.11.

I'd only like to report this, I'm not sure how the release process works for the pip packages. 
But maybe 3.11 will be the target version for jazzy (I think there is an [error here](https://www.ros.org/reps/rep-2000.html#jazzy-jalisco-may-2024-may-2029)) and more of this warnings will pop up soon.

```
# pip list | grep colcon
colcon-argcomplete                   0.3.3
colcon-bash                          0.4.2
colcon-cd                            0.1.1
colcon-cmake                         0.2.28
colcon-common-extensions             0.2.1
colcon-core                          0.15.1
colcon-defaults                      0.2.8
colcon-devtools                      0.2.3
colcon-library-path                  0.2.1
colcon-metadata                      0.2.5
colcon-mixin                         0.2.0
colcon-notification                  0.2.15
colcon-output                        0.2.12
colcon-package-information           0.3.3
colcon-package-selection             0.2.10
colcon-parallel-executor             0.2.4
colcon-pkg-config                    0.1.0
colcon-powershell                    0.4.0
colcon-python-setup-py               0.2.8
colcon-recursive-crawl               0.2.3
colcon-ros                           0.4.1
colcon-test-result                   0.3.8
colcon-zsh                           0.5.0
```

**Comment by cottsay** [comment]
The pip package for colcon-devtools 0.2.5 was released in October: https://pypi.org/project/colcon-devtools/0.2.5/

How are you installing colcon?

**Comment by christophfroehlich** [comment]
Ah, I realized now that it is installed with apt as dependency of `python3-colcon-common-extensions`
```
# apt info python3-colcon-devtools
Package: python3-colcon-devtools
Version: 0.2.3-2
```
https://packages.debian.org/bookworm/python3-colcon-devtools with 0.2.3 released.

**Comment by cottsay** [comment]
Ah, there's nothing I can do to help then. I have no more influence over Debian's packaging choices than you do.

It is unfortunate that they updated to `>= colcon-core-0.13.0` but not `>= colcon-devtools-0.2.3` which was released 3 days later. Even weirder that they updated colcon-core again and still didn't update colcon-devtools. I would have thought that the tests would fail from the deprecation warning...maybe they never even tried to build it after updating colcon-core.

:shrug:

**Comment by cottsay** [comment]
I'm going to close this issue here since this is a debian packaging problem. Feel free to open a ticket there.

**Comment by christophfroehlich** [comment]
ok, strange. Then I'll have to deal with pyenv and install it with pip I guess.
